name: Build and deploy

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Set up Docker Compose
              uses: Azure/docker-compose@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
                  compose-file: docker-compose.yml

            - name: Build and deploy
              uses: Azure/docker-compose@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}
                  compose-file: docker-compose.yml
                  action: up
