# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - telegram-manager-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_db89f4c929334bac901c9664f0ae7f7b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_050caee213dc46b6b58b4fe9b377ddbf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_db89f4c929334bac901c9664f0ae7f7b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'telegram-manager-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_43be2a6177aa4872ab0f90571e737a72 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_db89f4c929334bac901c9664f0ae7f7b }}/appsvc/staticsite:${{ github.sha }}'