# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - telegram-manager-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc540d4984dd466faee15487c0240b82 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1849089135ce4594bc17e8a81a31f991 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bc540d4984dd466faee15487c0240b82 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'telegram-manager-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3e5939d7a9fe4b6485d4e46338dce3b4 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bc540d4984dd466faee15487c0240b82 }}/appsvc/staticsite:${{ github.sha }}'