# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - spectral-telegram-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://spectralregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fdd13a5e99a343ddaddd9c82131ca3e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_08859b81368443328b004353a306fbcd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: spectralregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fdd13a5e99a343ddaddd9c82131ca3e0 }}/spectralregistry/spectral-api-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'spectral-telegram-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d620a56b69854720a43da48fd45d4f68 }}
        images: 'spectralregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fdd13a5e99a343ddaddd9c82131ca3e0 }}/spectralregistry/spectral-api-image:${{ github.sha }}'