name: Trigger auto deployment for spectral-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spectral-api-AutoDeployTrigger-e97a2840-126f-41b9-92d5-b01ea61145a7.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPECTRALAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: spectral.azurecr.io
          registryUsername: ${{ secrets.SPECTRALAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPECTRALAPI_REGISTRY_PASSWORD }}
          containerAppName: spectral-api
          resourceGroup: TelegramSpectral
          imageToBuild: spectral.azurecr.io/spectral-api:${{ github.sha }}
          

     

